version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres # hostname / address
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} # maintenance database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    networks:
      - pgnet

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - pgnet

  dbt-core:
    build:
      context: .                # Diretório atual, onde está o Dockerfile
      dockerfile: Dockerfile
    container_name: dbt-core
    restart: always
    volumes:
      - ./dbt:/usr/app/northwind   # Seu projeto dbt local → dentro do container
      - ./profiles.yml:/root/.dbt/profiles.yml   # profile do DBT
    environment:
      DB_HOST_PROD: ${DB_HOST_PROD}
      DB_USER_PROD: ${DB_USER_PROD}
      DB_PASS_PROD: ${DB_PASS_PROD}
      DB_PORT_PROD: ${DB_PORT_PROD}
      DB_NAME_PROD: ${DB_NAME_PROD}
      DB_SCHEMA_PROD: ${DB_SCHEMA_PROD}
      DB_THREADS_PROD: ${DB_THREADS_PROD}
    ports:
      - "8081:8081"                # Porta exposta pelo Dockerfile
    networks:
      - pgnet
    depends_on:
      - postgres                   # Garantir que o banco esteja no ar antes de rodar DBT

volumes:
  pgdata:
  pgadmindata:

networks:
  pgnet:
    driver: bridge